server:
  port: 8080
spring:
  ai:
    openai:
      api-key: sk-3DRp9oFqDQEdkxPLuHRzJoNEx9IPSqWbZWRGMvHdG4cVmY91
      base-url: https://api.chatanywhere.tech
      chat:
        options:
          model: gpt-4o-mini