server:
  port: 9527
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  application:
    name: examples
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.chatanywhere.tech